// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::acquired_card_type::AcquiredCard;
use super::card_type::Card;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `acquired_card`.
///
/// Obtain a handle from the [`AcquiredCardTableAccess::acquired_card`] method on [`super::RemoteTables`],
/// like `ctx.db.acquired_card()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.acquired_card().on_insert(...)`.
pub struct AcquiredCardTableHandle<'ctx> {
    imp: __sdk::TableHandle<AcquiredCard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `acquired_card`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AcquiredCardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AcquiredCardTableHandle`], which mediates access to the table `acquired_card`.
    fn acquired_card(&self) -> AcquiredCardTableHandle<'_>;
}

impl AcquiredCardTableAccess for super::RemoteTables {
    fn acquired_card(&self) -> AcquiredCardTableHandle<'_> {
        AcquiredCardTableHandle {
            imp: self.imp.get_table::<AcquiredCard>("acquired_card"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AcquiredCardInsertCallbackId(__sdk::CallbackId);
pub struct AcquiredCardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AcquiredCardTableHandle<'ctx> {
    type Row = AcquiredCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AcquiredCard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AcquiredCardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AcquiredCardInsertCallbackId {
        AcquiredCardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AcquiredCardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AcquiredCardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AcquiredCardDeleteCallbackId {
        AcquiredCardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AcquiredCardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AcquiredCard>("acquired_card");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AcquiredCard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AcquiredCard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
