// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::acquired_card_type::AcquiredCard;
use super::pokemon_type::Pokemon;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AcquiredPokemon {
    pub pokemon: Pokemon,
    pub cards_acquired: Vec<AcquiredCard>,
}

impl __sdk::InModule for AcquiredPokemon {
    type Module = super::RemoteModule;
}
