// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_type::Card;
use super::offer_type_type::OfferType;
use super::user_type::User;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Offer {
    pub id: String,
    pub owner: User,
    pub offer_type: OfferType,
    pub offers: Vec<Card>,
    pub requests: Vec<Card>,
}

impl __sdk::InModule for Offer {
    type Module = super::RemoteModule;
}
