// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_type::Card;
use super::list_type_type::ListType;
use super::pokemon_type::Pokemon;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PokemonRestriction {
    pub pokemon: Pokemon,
    pub list_type: ListType,
    pub list: Vec<Card>,
}

impl __sdk::InModule for PokemonRestriction {
    type Module = super::RemoteModule;
}
