// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pokemon_type::Pokemon;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pokemon`.
///
/// Obtain a handle from the [`PokemonTableAccess::pokemon`] method on [`super::RemoteTables`],
/// like `ctx.db.pokemon()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pokemon().on_insert(...)`.
pub struct PokemonTableHandle<'ctx> {
    imp: __sdk::TableHandle<Pokemon>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pokemon`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PokemonTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PokemonTableHandle`], which mediates access to the table `pokemon`.
    fn pokemon(&self) -> PokemonTableHandle<'_>;
}

impl PokemonTableAccess for super::RemoteTables {
    fn pokemon(&self) -> PokemonTableHandle<'_> {
        PokemonTableHandle {
            imp: self.imp.get_table::<Pokemon>("pokemon"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PokemonInsertCallbackId(__sdk::CallbackId);
pub struct PokemonDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PokemonTableHandle<'ctx> {
    type Row = Pokemon;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Pokemon> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PokemonInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PokemonInsertCallbackId {
        PokemonInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PokemonInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PokemonDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PokemonDeleteCallbackId {
        PokemonDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PokemonDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Pokemon>("pokemon");
    _table.add_unique_constraint::<i16>("id", |row| &row.id);
}
pub struct PokemonUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PokemonTableHandle<'ctx> {
    type UpdateCallbackId = PokemonUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PokemonUpdateCallbackId {
        PokemonUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PokemonUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Pokemon>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Pokemon>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `pokemon`,
/// which allows point queries on the field of the same name
/// via the [`PokemonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pokemon().id().find(...)`.
pub struct PokemonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Pokemon, i16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PokemonTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pokemon`.
    pub fn id(&self) -> PokemonIdUnique<'ctx> {
        PokemonIdUnique {
            imp: self.imp.get_unique_constraint::<i16>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PokemonIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i16) -> Option<Pokemon> {
        self.imp.find(col_val)
    }
}
