// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::set_images_type::SetImages;
use super::set_type::Set;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `set`.
///
/// Obtain a handle from the [`SetTableAccess::set`] method on [`super::RemoteTables`],
/// like `ctx.db.set()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.set().on_insert(...)`.
pub struct SetTableHandle<'ctx> {
    imp: __sdk::TableHandle<Set>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `set`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SetTableHandle`], which mediates access to the table `set`.
    fn set(&self) -> SetTableHandle<'_>;
}

impl SetTableAccess for super::RemoteTables {
    fn set(&self) -> SetTableHandle<'_> {
        SetTableHandle {
            imp: self.imp.get_table::<Set>("set"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SetInsertCallbackId(__sdk::CallbackId);
pub struct SetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SetTableHandle<'ctx> {
    type Row = Set;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Set> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SetInsertCallbackId {
        SetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SetDeleteCallbackId {
        SetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Set>("set");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct SetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SetTableHandle<'ctx> {
    type UpdateCallbackId = SetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SetUpdateCallbackId {
        SetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Set>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Set>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `set`,
/// which allows point queries on the field of the same name
/// via the [`SetIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.set().id().find(...)`.
pub struct SetIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Set, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SetTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `set`.
    pub fn id(&self) -> SetIdUnique<'ctx> {
        SetIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SetIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Set> {
        self.imp.find(col_val)
    }
}
