// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddPokemonArgs {
    pub id: i16,
    pub name: String,
}

impl From<AddPokemonArgs> for super::Reducer {
    fn from(args: AddPokemonArgs) -> Self {
        Self::AddPokemon {
            id: args.id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for AddPokemonArgs {
    type Module = super::RemoteModule;
}

pub struct AddPokemonCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_pokemon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_pokemon {
    /// Request that the remote module invoke the reducer `add_pokemon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_pokemon`] callbacks.
    fn add_pokemon(&self, id: i16, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_pokemon`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddPokemonCallbackId`] can be passed to [`Self::remove_on_add_pokemon`]
    /// to cancel the callback.
    fn on_add_pokemon(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i16, &String) + Send + 'static,
    ) -> AddPokemonCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_pokemon`],
    /// causing it not to run in the future.
    fn remove_on_add_pokemon(&self, callback: AddPokemonCallbackId);
}

impl add_pokemon for super::RemoteReducers {
    fn add_pokemon(&self, id: i16, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_pokemon", AddPokemonArgs { id, name })
    }
    fn on_add_pokemon(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i16, &String) + Send + 'static,
    ) -> AddPokemonCallbackId {
        AddPokemonCallbackId(self.imp.on_reducer(
            "add_pokemon",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddPokemon { id, name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, name)
            }),
        ))
    }
    fn remove_on_add_pokemon(&self, callback: AddPokemonCallbackId) {
        self.imp.remove_on_reducer("add_pokemon", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_pokemon`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_pokemon {
    /// Set the call-reducer flags for the reducer `add_pokemon` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_pokemon(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_pokemon for super::SetReducerFlags {
    fn add_pokemon(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_pokemon", flags);
    }
}
