// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddUserArgs {
    pub name: String,
    pub email: String,
}

impl From<AddUserArgs> for super::Reducer {
    fn from(args: AddUserArgs) -> Self {
        Self::AddUser {
            name: args.name,
            email: args.email,
        }
    }
}

impl __sdk::InModule for AddUserArgs {
    type Module = super::RemoteModule;
}

pub struct AddUserCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_user {
    /// Request that the remote module invoke the reducer `add_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_user`] callbacks.
    fn add_user(&self, name: String, email: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_user`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddUserCallbackId`] can be passed to [`Self::remove_on_add_user`]
    /// to cancel the callback.
    fn on_add_user(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AddUserCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_user`],
    /// causing it not to run in the future.
    fn remove_on_add_user(&self, callback: AddUserCallbackId);
}

impl add_user for super::RemoteReducers {
    fn add_user(&self, name: String, email: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_user", AddUserArgs { name, email })
    }
    fn on_add_user(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AddUserCallbackId {
        AddUserCallbackId(self.imp.on_reducer(
            "add_user",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddUser { name, email },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, email)
            }),
        ))
    }
    fn remove_on_add_user(&self, callback: AddUserCallbackId) {
        self.imp.remove_on_reducer("add_user", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_user`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_user {
    /// Set the call-reducer flags for the reducer `add_user` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_user(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_user for super::SetReducerFlags {
    fn add_user(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_user", flags);
    }
}
