// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::acquired_card_type::AcquiredCard;
use super::acquired_pokemon_type::AcquiredPokemon;
use super::card_type::Card;
use super::offer_type::Offer;
use super::pokemon_restriction_type::PokemonRestriction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Binder {
    pub id: String,
    pub owner: u32,
    pub name: String,
    pub desired_pokemon_ids: Vec<String>,
    pub acquired_pokemons: Vec<AcquiredPokemon>,
    pub pokemon_restrictions: Vec<PokemonRestriction>,
    pub desired_cards: Vec<Card>,
    pub acquired_cards: Vec<AcquiredCard>,
    pub offers: Vec<Offer>,
}

impl __sdk::InModule for Binder {
    type Module = super::RemoteModule;
}
