// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::acquired_card_type::AcquiredCard;
use super::acquired_pokemon_type::AcquiredPokemon;
use super::binder_type::Binder;
use super::card_type::Card;
use super::offer_type::Offer;
use super::pokemon_restriction_type::PokemonRestriction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `binder`.
///
/// Obtain a handle from the [`BinderTableAccess::binder`] method on [`super::RemoteTables`],
/// like `ctx.db.binder()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.binder().on_insert(...)`.
pub struct BinderTableHandle<'ctx> {
    imp: __sdk::TableHandle<Binder>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `binder`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BinderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BinderTableHandle`], which mediates access to the table `binder`.
    fn binder(&self) -> BinderTableHandle<'_>;
}

impl BinderTableAccess for super::RemoteTables {
    fn binder(&self) -> BinderTableHandle<'_> {
        BinderTableHandle {
            imp: self.imp.get_table::<Binder>("binder"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BinderInsertCallbackId(__sdk::CallbackId);
pub struct BinderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BinderTableHandle<'ctx> {
    type Row = Binder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Binder> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BinderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BinderInsertCallbackId {
        BinderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BinderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BinderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BinderDeleteCallbackId {
        BinderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BinderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Binder>("binder");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct BinderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BinderTableHandle<'ctx> {
    type UpdateCallbackId = BinderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BinderUpdateCallbackId {
        BinderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BinderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Binder>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Binder>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `binder`,
/// which allows point queries on the field of the same name
/// via the [`BinderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.binder().id().find(...)`.
pub struct BinderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Binder, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BinderTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `binder`.
    pub fn id(&self) -> BinderIdUnique<'ctx> {
        BinderIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BinderIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Binder> {
        self.imp.find(col_val)
    }
}
