// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::card_images_type::CardImages;
use super::card_type::Card;
use super::set_type::Set;
use super::tcg_player_type::TcgPlayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `card`.
///
/// Obtain a handle from the [`CardTableAccess::card`] method on [`super::RemoteTables`],
/// like `ctx.db.card()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.card().on_insert(...)`.
pub struct CardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Card>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `card`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CardTableHandle`], which mediates access to the table `card`.
    fn card(&self) -> CardTableHandle<'_>;
}

impl CardTableAccess for super::RemoteTables {
    fn card(&self) -> CardTableHandle<'_> {
        CardTableHandle {
            imp: self.imp.get_table::<Card>("card"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CardInsertCallbackId(__sdk::CallbackId);
pub struct CardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CardTableHandle<'ctx> {
    type Row = Card;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Card> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardInsertCallbackId {
        CardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardDeleteCallbackId {
        CardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Card>("card");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct CardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CardTableHandle<'ctx> {
    type UpdateCallbackId = CardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CardUpdateCallbackId {
        CardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Card>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Card>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `card`,
/// which allows point queries on the field of the same name
/// via the [`CardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.card().id().find(...)`.
pub struct CardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Card, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `card`.
    pub fn id(&self) -> CardIdUnique<'ctx> {
        CardIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Card> {
        self.imp.find(col_val)
    }
}
