// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::card_images_type::CardImages;
use super::set_type::Set;
use super::tcg_player_type::TcgPlayer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Card {
    pub id: String,
    pub supertype: String,
    pub subtypes: Vec<String>,
    pub set: Set,
    pub number: String,
    pub artist: String,
    pub rarity: String,
    pub national_pokedex_numbers: Vec<i16>,
    pub images: CardImages,
    pub tcg_player: TcgPlayer,
}

impl __sdk::InModule for Card {
    type Module = super::RemoteModule;
}
