// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteUserArgs {
    pub id: u32,
}

impl From<DeleteUserArgs> for super::Reducer {
    fn from(args: DeleteUserArgs) -> Self {
        Self::DeleteUser { id: args.id }
    }
}

impl __sdk::InModule for DeleteUserArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteUserCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_user {
    /// Request that the remote module invoke the reducer `delete_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_user`] callbacks.
    fn delete_user(&self, id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_user`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteUserCallbackId`] can be passed to [`Self::remove_on_delete_user`]
    /// to cancel the callback.
    fn on_delete_user(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteUserCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_user`],
    /// causing it not to run in the future.
    fn remove_on_delete_user(&self, callback: DeleteUserCallbackId);
}

impl delete_user for super::RemoteReducers {
    fn delete_user(&self, id: u32) -> __sdk::Result<()> {
        self.imp.call_reducer("delete_user", DeleteUserArgs { id })
    }
    fn on_delete_user(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteUserCallbackId {
        DeleteUserCallbackId(self.imp.on_reducer(
            "delete_user",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteUser { id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id)
            }),
        ))
    }
    fn remove_on_delete_user(&self, callback: DeleteUserCallbackId) {
        self.imp.remove_on_reducer("delete_user", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_user`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_user {
    /// Set the call-reducer flags for the reducer `delete_user` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_user(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_user for super::SetReducerFlags {
    fn delete_user(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_user", flags);
    }
}
