// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct NewBinderArgs {
    pub id: String,
    pub name: String,
    pub owner: u32,
}

impl From<NewBinderArgs> for super::Reducer {
    fn from(args: NewBinderArgs) -> Self {
        Self::NewBinder {
            id: args.id,
            name: args.name,
            owner: args.owner,
        }
    }
}

impl __sdk::InModule for NewBinderArgs {
    type Module = super::RemoteModule;
}

pub struct NewBinderCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `new_binder`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait new_binder {
    /// Request that the remote module invoke the reducer `new_binder` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_new_binder`] callbacks.
    fn new_binder(&self, id: String, name: String, owner: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `new_binder`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`NewBinderCallbackId`] can be passed to [`Self::remove_on_new_binder`]
    /// to cancel the callback.
    fn on_new_binder(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &u32) + Send + 'static,
    ) -> NewBinderCallbackId;
    /// Cancel a callback previously registered by [`Self::on_new_binder`],
    /// causing it not to run in the future.
    fn remove_on_new_binder(&self, callback: NewBinderCallbackId);
}

impl new_binder for super::RemoteReducers {
    fn new_binder(&self, id: String, name: String, owner: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("new_binder", NewBinderArgs { id, name, owner })
    }
    fn on_new_binder(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &u32) + Send + 'static,
    ) -> NewBinderCallbackId {
        NewBinderCallbackId(self.imp.on_reducer(
            "new_binder",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::NewBinder { id, name, owner },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, name, owner)
            }),
        ))
    }
    fn remove_on_new_binder(&self, callback: NewBinderCallbackId) {
        self.imp.remove_on_reducer("new_binder", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `new_binder`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_new_binder {
    /// Set the call-reducer flags for the reducer `new_binder` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn new_binder(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_new_binder for super::SetReducerFlags {
    fn new_binder(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("new_binder", flags);
    }
}
