// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::card_type::Card;
use super::offer_type::Offer;
use super::offer_type_type::OfferType;
use super::user_type::User;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `offer`.
///
/// Obtain a handle from the [`OfferTableAccess::offer`] method on [`super::RemoteTables`],
/// like `ctx.db.offer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.offer().on_insert(...)`.
pub struct OfferTableHandle<'ctx> {
    imp: __sdk::TableHandle<Offer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `offer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OfferTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OfferTableHandle`], which mediates access to the table `offer`.
    fn offer(&self) -> OfferTableHandle<'_>;
}

impl OfferTableAccess for super::RemoteTables {
    fn offer(&self) -> OfferTableHandle<'_> {
        OfferTableHandle {
            imp: self.imp.get_table::<Offer>("offer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OfferInsertCallbackId(__sdk::CallbackId);
pub struct OfferDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OfferTableHandle<'ctx> {
    type Row = Offer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Offer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OfferInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OfferInsertCallbackId {
        OfferInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OfferInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OfferDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OfferDeleteCallbackId {
        OfferDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OfferDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Offer>("offer");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct OfferUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OfferTableHandle<'ctx> {
    type UpdateCallbackId = OfferUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OfferUpdateCallbackId {
        OfferUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OfferUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Offer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Offer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `offer`,
/// which allows point queries on the field of the same name
/// via the [`OfferIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.offer().id().find(...)`.
pub struct OfferIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Offer, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OfferTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `offer`.
    pub fn id(&self) -> OfferIdUnique<'ctx> {
        OfferIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OfferIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Offer> {
        self.imp.find(col_val)
    }
}
