// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::set_images_type::SetImages;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Set {
    pub id: String,
    pub name: String,
    pub printed_total: i16,
    pub total: i16,
    pub release_date: String,
    pub images: SetImages,
}

impl __sdk::InModule for Set {
    type Module = super::RemoteModule;
}
